version: '2'
services:
    portainer:
        image: portainer/portainer
        ports:
            - "9000:9000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        command: --swarm
    visualizer:
        image: manomarks/visualizer
        ports:
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
